### ISSUE TITLE
Error whilst downloading from GitHub and colorChecker question

### ISSUE THREAD

**Issue by EveTC** [StevenVB12/patternize#13]
Hello,

Thank you for designing this package. It looks as though it will be really useful and I am looking forward to trying it!

Just a couple of questions:

1) I am trying to download Patternize from gitHub follwing the instructions provided:
`install.packages("devtools")
library(devtools)
install_github("StevenVB12/patternize")`
However I keep receiving this error:
`Error in read.dcf(path) : 
  Found continuation line starting '    obtained from im ...' at begin of record.`
Do you know what ight be causing this error? My apologies if it is a simple fix and I have missed something.

2) Can patternize be adapted to use other ColorCheckers or is it only compatible with the MacBeth ColorChecker?

Thank you for your help.
Eve

**Comment by StevenVB12** [comment]
Hi Eve,

not sure what is causing the download problem, but at this time, the most resent version is on CRAN. Please just run install.package("patternize").

The MacBeth colorchecker is the only one that I have implemented so far. I'm quite swamped at this time, but if you give me the specs of the colorchecker you want to use, I will put it on my list of things to do (but please have patience with me).

Hope this helps and let me know if you run into any other problems.

Cheers,
Steven

**Comment by StevenVB12** [comment]
Hi Eve,

I added functionalities for the ColorGauge Micro Analyzer colorChecker. I haven't tested it extensively, but I hope it works correctly for you.

It is only available when downloading from github at this point (and not through the R shiny app):

install.packages("devtools")
library(devtools)
install_github("StevenVB12/patternize")

If you still have the read.dcf() error, please try to clone/download the package (https://github.com/StevenVB12/patternize) and run:

install.packages("devtools")
library(devtools)
build("~/put/the/package/path/here")


You can run the colorChecker function as follows:

colorChecker(c('Calibrate_example_2'), extension = '.jpg', colorCheckerType = 'ColorGauge Micro Analyzer')

If you get an error message that says:

Error in R(im) : could not find function "R"

then run:

library(imager)

Let me know if it works or not!

Steven

**Comment by EveTC** [comment]
Hi Steven,

Thank you so much for adding the ColorGauge Micro Analyser to the package and so quickly. I will have a go with it and let you know if it works or if I come across any problems.

Thanks again,
Eve

**Comment by EveTC** [comment]
Hi Steven,

I hope you had a lovely Christmas!

I have just been testing the ColorGauge Micro Analyser and just to let you know that the order of colours you click to outline is currently:
 `[1] "Click on the outer corners of the ColorGauge Micro Analyzer ColorChecker (1: ~brown, 2: ~cyan, 3: ~red, 4: ~purple)"` 
However, the colour patches align correctly in this order: 1: brown; 2: cyan; 3: purple; and 4) red. Otherwise it works well, thank you very much. 

Is there a way to automate the calibrating process, to save clicking on the corners each time? I will have over 1,000 pictures that need calibrating before looking at the colour and pattern variation.

**Comment by StevenVB12** [comment]
Hi Eve,

thanks for finding the mistake and happy holidays to you too!

Writing code for finding the colorChecker automatically would be pretty hard for me. I know it's possible, but it would take some smart way of finding the colorChecker pattern within the images.

On the other hand, if your colorChecker is always in the exact same spot, I could easily add some code so that you only have to set the coordinates ones. Would that help?

Steven

**Comment by EveTC** [comment]
Hi Steven,

No worries, I am currently running calibration on a test sample of images and it is working well.

Yes that would be perfect! I always have the colourChecker on the right-hand side of the image and it won't/shouldn't be moved between images.

Thank you so much,
Eve

**Comment by EveTC** [comment]
Hi Steven,

I have been trying to draw the cartoon outline of one of my wings. However, even though I have inverted the Y axis on ImageJ (so that 0,0 is at the bottom left corner) when I export the XY coordinates (File >Save as > XY Coordinates...) and plot it in R the Y axis hasn't been reverted so my wing shape is not in the correct oreintation.

Have I missed a step to correct the Y axis? 

Thank you so much for your help,
Eve

**Comment by StevenVB12** [comment]
Hi Eve,

in that case, does it work when you set adjustCoords = FALSE?

Steven

**Comment by StevenVB12** [comment]
Hi Eve,

I updated the colorChecker function. If you now set 'fixedCorners = TRUE', you will only have to set the corner coordinates for the first image and the function will loop through all the images in the IDList.

Let me know if this works for you or if there's anything I can do to make your life easier.

Cheers,
Steven

**Comment by EveTC** [comment]
Hi Steven,

It works perfectly, thank you so much.

I will have another go at making the cartoon outline etc.

Thanks again and Happy New Year!
Eve

**Comment by EveTC** [comment]
Hello Steven,

The package is working great and it is interesting looking at the variance in pattern for my species. However, I was wondering if there is a way to look at the overall colour? - For example to see if the overall colour gets darker further north, and/or if the contrast of the main colour to pattern increases?

Currently my understanding is that the RGB method will look at the differences between the RGB value (and offset) included, and hence is best for specific sections of the wing. Using the K-means method, you get different rasters for each cluster (equates to groups of colours) you have set (and so goes more towards answering my question). However,  as the pattern I am investigating is not as distinct as the examples provided I need a high setting of K, which makes it tricky to interpret the large amount of rasters produced and which one refers to what RGB value. 

Does patternize have the capability to address the above question? Or is it best to use another tool and if so do you know of any that I could implement?

I look forward to hearing yor suggestions.
Thank you again,
Eve

**Comment by StevenVB12** [comment]
Hi Eve,

if I understand your question correctly, patternize doesn't really offer great capabilities of studying quantitative variation in pixel intensities. It rather tries to classify the pixels as belonging to a certain pattern. For those type of analysis, I would suggest imageJ/Fiji to study the raw RGB values.

Although, it should be possible to set a fixed threshold and see if more pixels get include when you go e.g. north.

Hope this helps.

Steven

**Comment by EveTC** [comment]
Hi Steven,

Sorry for my delay in responding. 

Thank you for your answer - I thought this was the case. I will have a look at ImageJ/FiJi to address this question.

Thank you again for all your help.
Eve
